name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

permissions:
  contents: read

concurrency:
  group: liquidity-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  forge-tests:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          echo Foundry profile: $FOUNDRY_PROFILE
          forge --version
          forge build --sizes
        id: build

      - name: Build rust project
        run: ./script/build_rust.sh
        id: build-rust

      - name: Run Forge tests
        run: forge test --isolate -vvv
        id: test
        env:
          FORGE_SNAPSHOT_CHECK: true
          QUICKNODE_RPC_URL: ${{ secrets.QUICKNODE_RPC_URL }}
